name: 'tns'
channels:
  - conda-forge
dependencies:
  - terraform
  - jq
  - boto3
  - awscli
  - python
  - pyarrow
  - polars
  - polars-st
  - gdal
  - geopandas
  - libgdal-arrow-parquet
  - pyogrio
  - duckdb
  - pytest