name: 'tns'
channels:
  - conda-forge
dependencies:
  - terraform
  - boto3
  - python
  - geopandas
  - pyarrow
  - python<3.14
  - jq
  - gdal
  - libgdal-arrow-parquet
  - duckdb
  - polars
  - polars-st