#!/usr/bin/env bash
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

CMD="terraform destroy"

VAR_PATH=$1
if [[ $VAR_PATH != "" ]]; then
    VAR_PATH=$(realpath $VAR_PATH)
    echo "VAR_PATH adjusted to ${VAR_PATH}"
    CMD="${CMD} --var-file ${VAR_PATH}"
fi

# Tearing down architecture, will prompt for confirmation
echo $CMD
cd $SCRIPT_DIR/../terraform
eval $CMD
# if this fails, don't continue to removing build files
if [[ $? -eq 1 ]]; then
    echo "Failed to destroy terraform. Exiting."
    exit 1
fi
