#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
source "$SCRIPT_DIR/pixi_env"

CMD=(tns_pixi_exec terraform destroy)

VAR_PATH="${1:-}"
if [[ -n "$VAR_PATH" ]]; then
    VAR_PATH=$(realpath "$VAR_PATH")
    echo "VAR_PATH adjusted to ${VAR_PATH}"
    CMD+=(--var-file "$VAR_PATH")
fi
shift $(( $# > 0 ? 1 : 0 ))
if (( $# > 0 )); then
    CMD+=("$@")
fi

# Tearing down architecture, will prompt for confirmation
printf '%s\n' "${CMD[*]}"
cd "$SCRIPT_DIR/../terraform"
"${CMD[@]}"

# Removing build files, will prompt for confirmation
BUILD_PATH="${SCRIPT_DIR}/../build"
read -p "Deleting ${BUILD_PATH}. You will need to run 'init' again to recreate these. Continue?(Y/n) " confirm
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
    rm -rf "$BUILD_PATH"
    exit 0
fi
exit 1
