#!/usr/bin/env bash
set -euo pipefail

CMD=(terraform apply)

VAR_PATH="${1:-}"
if [[ -n "${VAR_PATH}" ]]; then
    VAR_PATH=$(realpath "$VAR_PATH")
    echo "VAR_PATH adjusted to ${VAR_PATH}"
    CMD+=(--var-file "$VAR_PATH")
fi
printf '%s\n' "${CMD[*]}"

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

echo "$SCRIPT_DIR"

cd "$SCRIPT_DIR/../terraform"
"${CMD[@]}"
